repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # sempre use uma versão fixa
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
