name: Node.js Dependency Check

on: [push]

jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: dependency_check_nodejs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js v14
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'nodejs-app'
          path: '.'                         # Path to scan (e.g., where package.json is)
          format: 'HTML'                    # Report format
          out: 'reports'                    # Output folder
          args: >
            --failOnCVSS 7                  # Optional: fail the job if vulnerabilities ≥ CVSS 7
            --enableRetired                 # Optional: detect deprecated packages

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: Depcheck Report
          path: reports
