name: Dependency Check CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  depcheck:
    runs-on: ubuntu-latest
    name: Run Dependency Check with Node 14 and bcrypt

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js v14
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        id: depcheck
        with:
          project: 'dvna-sast-validate'
          path: '.'
          format: 'HTML'
          out: 'dependency-check-report'
          args: >
            --failOnCVSS 7
            --enableRetired

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report/dependency-check-report.html
