name: Gitleaks Secret Scan

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"  # diário às 4h da manhã

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  gitleaks:
    name: Run Gitleaks secret scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Gitleaks CLI
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.18.1/gitleaks_8.18.1_linux_x64.tar.gz -o gitleaks.tar.gz
          tar -xzf gitleaks.tar.gz
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/

      - name: Run Gitleaks scan (fail if leaks found)
        run: |
          gitleaks detect --source . \
            --report-format sarif \
            --report-path gitleaks.sarif
          exit_code=$?
          echo "GITLEAKS_EXIT_CODE=$exit_code" >> $GITHUB_ENV

      - name: Upload Gitleaks SARIF report to GitHub Code Scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif

      - name: Show link to Code Scanning results
        run: |
          echo "🔍 Veja os resultados: https://github.com/${{ github.repository }}/security/code-scanning"

      - name: Fail if secrets were found
        if: env.GITLEAKS_EXIT_CODE != '0'
        run: |
          echo "::error::🚨 Vazamentos de segredo foram encontrados!"
          exit 1
