name: Trivy Docker Scan 

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  actions: read
  contents: read
  security-events: write 

jobs:
  trivy:
    name: Run Trivy scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Trivy (via script oficial)
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Build Docker image
        run: docker build -t my-app:latest .

      - name: Run Trivy scan and generate SARIF
        run: trivy image --format sarif -o trivy-results.sarif --exit-code 1 --severity CRITICAL,HIGH my-app:latest #pipe
        continue-on-error: true

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif

      - name: 🔍 Show link to Code Scanning results
        run: |
          echo ""
          echo "✅ Trivy scan concluído."
          echo "🔗 Veja os alertas em: https://github.com/${{ github.repository }}/security/code-scanning"
